import { describe, it, expect } from 'vitest'
import type { NarrationEntry } from '../../shared/types'
import { isRenderableTurn } from './chat-turns'

const e = (kind: string, text: string): NarrationEntry =>
  ({ kind, text, timestamp: '2026-07-28T10:00:00Z' } as NarrationEntry)

describe('isRenderableTurn', () => {
  it('renders NOTHING for a signature-only thinking block', () => {
    // 100% of real thinking blocks look like this (326 transcripts, 17,682 blocks, all empty).
    // A collapsible Thought block over this data is a disclosure that can never open.
    expect(isRenderableTurn(e('thinking', ''))).toBe(false)
    expect(isRenderableTurn(e('thinking', '   \n  '))).toBe(false)
  })

  it('still renders a thinking block that HAS text, so the path lights up if it ever arrives', () => {
    expect(isRenderableTurn(e('thinking', 'The routing lives in a useEffect.'))).toBe(true)
  })

  it('keeps real prompts and answers, drops Claude Code plumbing turns', () => {
    expect(isRenderableTurn(e('user', 'hi'))).toBe(true)
    expect(isRenderableTurn(e('text', 'Done.'))).toBe(true)
    expect(isRenderableTurn(e('user', '<local-command-stdout>Set model to Sonnet</local-command-stdout>'))).toBe(false)
    expect(isRenderableTurn(e('user', '<command-name>/model</command-name>'))).toBe(false)
  })

  // The gap that let a "regression" report be filed: every existing test checked the
  // PREDICATE, nothing checked it against what is actually persisted. These four are real
  // rows sampled from ~/.operator/chat.db, which holds 191 such rows across 33 sessions —
  // history written before the parser-side filter existed, and history can always predate a
  // parser change. The reading surface must never trust its input to have been filtered
  // upstream, so this guard is the durable one.
  it('drops injected rows ALREADY PERSISTED in chat.db', () => {
    const persisted = [
      '<task-notification>\n<task-id>bwzjz69uj</task-id>\n<tool-use-id>toolu_01…',
      '<local-command-caveat>Caveat: The messages below were generated by the user…',
      '<command-name>/compact</command-name>\n            <command-message>compact…',
      '<local-command-stdout>\x1b[2mCompacted (ctrl+o to see full summary)\x1b[22m',
    ]
    for (const text of persisted) {
      expect(isRenderableTurn(e('user', text)), text.slice(0, 40)).toBe(false)
    }
  })

  it('drops kinds the reading surface does not carry', () => {
    expect(isRenderableTurn(e('tool', 'Edit'))).toBe(false)
  })
})
